import type { GlossaryTerm } from './schema.ts'

// Migrated from apps/portfolio/src/data/glossaryData.js (Confluence export). Details are Markdown.
export const glossary = [
  {
    id: "adc",
    term: "ADC",
    fullForm: "Authorization Decision Control",
    category: "General",
    details: "Authorization Decision Control",
  },
  {
    id: "atc",
    term: "ATC",
    fullForm: "Application Transaction Counter",
    category: "General",
    details: "* **Purpose:** The ATC serves as a unique identifier for each transaction, helping to prevent replay attacks and ensure transaction integrity.\n\n* **Incrementing:** The card chip increments the ATC at the beginning of each transaction.\n\n* **Value Range:** The ATC value ranges from 0x0000 to 0xFFFF (0 to 65535).\n\n* **Security:** If a transaction attempts to use an ATC value that's already been used or is lower than the last used ATC, the transaction may be denied as a potential replay attack or clone card issue, as Pismo Developers Portal explains.\n\n* **ATC Update:** Issuers can update the ATC maintained at their end with the latest ATC from the chip on the card, according to Mastercard.",
  },
  {
    id: "cavv",
    term: "CAVV",
    fullForm: "Cardholder Authentication Verification Value",
    category: "General",
    details: "The Cardholder Authentication Verification Value (CAVV) is a cryptographic value generated during Visa Secure authentication, specifically within the 3-D Secure protocol. It serves as evidence that the cardholder's identity has been verified and links the issuer's authentication response with the subsequent authorization message. The CAVV is unique for each authentication transaction and is provided by the acquirer to the issuer during the authorization process",
  },
  {
    id: "tpdu",
    term: "TPDU",
    fullForm: "Transaction Protocol Data Unit",
    category: "Technology",
    details: "The Transaction Protocol Data Unit (TPDU) is an old-school packet-based protocol designed for transaction-oriented applications. On the OSI model it stands between the Transport Layer (e.g. X.25, TCP or UDP) and the Application Layer. It was originally designed for X.25-based dial-up payment devices to provide the ability to concentrate a large number of these into one central host connection.\n\nTPDU message has 3 parts:\n\n* **Protocol ID** – Access protocol for a TPDU message  \n* **Destination Address** – Routing information for reaching message’s destination  \n* **Source Address** – Routing information for getting back to message’s origin",
  },
  {
    id: "fcra",
    term: "FCRA",
    fullForm: "Fair Credit Reporting Act",
    category: "Finance",
    details: "The Fair Credit Reporting Act was originally passed in 1970. It was intended to shield consumers from the willful and/or negligent inclusion of erroneous data in their credit reports.",
  },
  {
    id: "otb",
    term: "OTB",
    fullForm: "Open To Buy",
    category: "Finance",
    details: "**OTB** (*Open To Buy*) refers to the **available credit** a cardholder can still spend on their credit card. It is calculated as:\n\n`OTB = Credit Limit - Current Balance`\n\nIn the context of credit cards:\n- **Credit Limit**: The maximum amount the issuer allows you to borrow.\n- **Current Balance**: The total of all posted transactions, including purchases, fees, and pending payments.\n\nFor example, if your credit limit is ₹1,00,000 and you've already spent ₹60,000, your OTB is ₹40,000. \n\n> 💡 *OTB helps track how much spending power remains on the card before reaching the limit.*",
  },
  {
    id: "ipm",
    term: "IPM",
    fullForm: "Integrated Product Messages",
    category: "Payments",
    details: "**IPM** (*Integrated Product Messages*) is a data exchange format used by **Mastercard** to communicate detailed clearing and settlement information for transactions. \n\nIt includes:\n- Transaction-level data (amount, date, location, currency)\n- Interchange fee details\n- Chargeback and dispute data\n\n**IPM files** are essential for reconciling transactions, reporting, and ensuring compliance across Mastercard's global payment network.\n\n> 📊 IPM ensures financial institutions and processors receive rich, structured data for each transaction in the Mastercard ecosystem.",
  },
  {
    id: "ucaf",
    term: "UCAF",
    fullForm: "Universal Cardholder Authentication Field",
    category: "Payments",
    details: "**UCAF** (*Universal Cardholder Authentication Field*) is a standardized authentication data field developed by **Mastercard** and supported by global card networks including **Visa**, **Verve**, and others through the **EMVCo** framework.\n\nIt is a critical part of the **3-D Secure (3DS)** ecosystem, used in **card-not-present** (CNP) transactions to:\n\n- Carry authentication data from the **Access Control Server (ACS)** to the card issuer\n- Embed cardholder identity verification results directly in the **authorization message**\n- Improve issuer decision-making and reduce **fraud and chargebacks**\n\nUCAF is used across multiple 3DS implementations:\n- **Mastercard** → Identity Check (3DS)\n- **Visa** → Visa Secure\n- **Verve** → Verve e-commerce 3DS via EMVCo-compliant solutions\n\n**Transaction Lifecycle with UCAF in 3DS**:\n1. Cardholder initiates a payment online.\n2. The ACS performs authentication (e.g., OTP, biometrics).\n3. The result (pass/fail, method) is encoded into the **UCAF**.\n4. UCAF is sent to the **issuer** as part of the authorization message.\n5. The issuer uses this to **approve/decline** the transaction.\n\n> 🔐 **UCAF** enables **frictionless, secure digital commerce** by ensuring authenticated transaction data is shared seamlessly across networks.",
  },
  {
    id: "aevv",
    term: "AEVV",
    fullForm: "American Express Verification Value",
    category: "General",
    details: "CSC is a series of numbers that, in addition to thebank card number, is printed (but notembossed) on acreditordebit card. CSC is used as a security feature forcard not present transactions, where apersonal identification number(PIN) cannot be manually entered by the cardholder.",
  },
  {
    id: "fema",
    term: "FEMA",
    fullForm: "Federal Emergency Management Agency",
    category: "General",
    details: "The agency's primary purpose is to coordinate the response to a disaster that has occurred in the United States. The governor of the state in which the disaster occurs must declare astate of emergency. FEMA is part of the Department of Homeland Security.",
  },
  {
    id: "scra",
    term: "SCRA",
    fullForm: "The SERVICEMEMBERS CIVIL RELIEF ACT",
    category: "Business",
    details: "The Servicemembers Civil Relief Act of 1940 protects U.S. citizens serving with allied military forces for the duration of a military conflict involving the United States. Its origins can be traced as far back as theCivil War.",
  },
  {
    id: "aav",
    term: "AAV",
    fullForm: "Account Authentication Value",
    category: "Finance",
    details: "Credit card authentication is the process of confirming that a person who is attempting to use a credit card for a transaction is who they say they are. It is not the same as credit card authorization, which also verifies other information, such as that the card account has a sufficientcredit lineto cover the transaction.",
  },
  {
    id: "mid",
    term: "MID",
    fullForm: "Merchant Identification Number",
    category: "General",
    details: "Merchant category codes (MCCs) are four-digit numbers that credit card issuers use to classify individual purchases. The codes serve a variety of purposes, including the calculation and issuance ofcredit card rewards.",
  },
  {
    id: "mcc",
    term: "MCC",
    fullForm: "Acceptor Business Code. Earlier it was known as merchant category code",
    category: "Technology",
    details: "Amerchant category code (MCC) is a four-digit number used for retail financial services to classify a business by the types of goods or services it provides. MCCs are assigned either by merchant type (e.g., one for hotels, one for office supply stores, etc.) or by merchant name.",
  },
  {
    id: "mti",
    term: "MTI",
    fullForm: "Message Type Indicator",
    category: "General",
    details: "The vast majority of transactions made when a customer uses a card to make a payment in a store (EFTPOS) use ISO 8583 at some point in the communication chain. In particular, theMastercard,VisaandVervenetworks base their authorization communications on the standard.",
  },
  {
    id: "mdes",
    term: "MDES",
    fullForm: "MasterCard Digital Enablement Service",
    category: "Technology",
    details: "Verifone sells merchant-operated, consumer-facing and self-service payment systems to the financial, retail, hospitality, petroleum, government and healthcare industries. Its products process a range of payment types, including signature and personal identification number (PIN)-baseddebit cards.",
  },
  {
    id: "bin",
    term: "BIN",
    fullForm: "Bank Identification Number",
    category: "General",
    details: "The BIN system helps financial institutions identify fraudulent or stolen payment cards and can help prevent identity theft. BINs can be found on various payment cards, including credit cards, charge cards, and debit cards. This set of numbers identifies thefinancial institutionthat issues the card.",
  },
  {
    id: "tid",
    term: "TID",
    fullForm: "Terminal Identification Number",
    category: "General",
    details: "The PIN has been the key to facilitating theprivate dataexchange between different data-processing centers in computer networks. PINs may be used to authenticate banking systems with cardholders, governments with citizens, enterprises with employees, and computers with users, among other uses.",
  },
  {
    id: "gcms",
    term: "GCMS",
    fullForm: "Global Clearing Management System",
    category: "Technology",
    details: "Clearing is necessary for the matching of all buy and sell orders in the market. It provides smoother and more efficient markets as parties can make transfers to the clearing corporation. Non-cleared trades can result insettlement risk.",
  },
  {
    id: "mds",
    term: "MDS",
    fullForm: "MasterCard Debit Switch",
    category: "Finance",
    details: "Switch was launched in 1988 byMidland Bank,National Westminster BankandThe Royal Bank of Scotland. It was then merged withMaestro, which is owned byMasterCard. Since then, Switch has been out of circulation.",
  },
  {
    id: "ocl",
    term: "OCL",
    fullForm: "Original Credit Limit",
    category: "Finance",
    details: "A credit limit is the maximum amount of credit a financial institution extends to a client on a credit card or aline of credit. Lenders usually set credit limits based on specific information about the credit-seeking applicant, including their income and employment status.",
  },
  {
    id: "php",
    term: "PHP",
    fullForm: "Payment History Profile",
    category: "Finance",
    details: "FICO scores range from 300 and 850, with anything 670 or above considered good or better. If your score is much lower than that, you will probably find it difficult to borrow money.",
  },
  {
    id: "dda",
    term: "DDA",
    fullForm: "Dynamic Data Authentication",
    category: "Technology",
    details: "EMV stands for \"Europay,Mastercard, andVisa\", the three companies that created the standard. Payment cards which comply with the EMV standard are often calledchip and PINorchip and signaturecards.",
  },
  {
    id: "aip",
    term: "AIP",
    fullForm: "Application Interchange Profile",
    category: "General",
    details: "EMV stands for \"Europay,Mastercard, andVisa\", the three companies that created the standard. Payment cards which comply with the EMV standard are often calledchip and PINorchip and signaturecards.",
  },
  {
    id: "cit",
    term: "CIT",
    fullForm: "Change In terms",
    category: "General",
    details: "Change is a commonly used term in the world of finance, though it has many names. In general, a change refers to a price difference that occurs between two points in time. Another word for change is volatility.",
  },
  {
    id: "srb",
    term: "SRB",
    fullForm: "Statement Revolving Balance",
    category: "General",
    details: "Revolving credit refers to a type of credit account that allows the borrower to repeatedly borrow up to a certain limit. Making payments reduces the balance owed and frees up credit, which can be used again.",
  },
  {
    id: "cfpb",
    term: "CFPB",
    fullForm: "Consumer Financial Protection Bureau",
    category: "General",
    details: "CFPB's jurisdiction includesbanks,credit unions, securities firms,payday lenders, mortgage-servicing operations,foreclosurerelief services,debt collectors, and for-profit colleges.",
  },
  {
    id: "stip",
    term: "STIP",
    fullForm: "Stand-In Processing",
    category: "General",
    details: "An ATM controller is key infrastructure in aninterbank network. A message may enter an ATMC from an ATM, another ATMC or a third party. An ATMC will examine the message, validate the PIN block if present, and then route the message according to the leading digits of the account number referenced.",
  },
  {
    id: "fpan",
    term: "FPAN",
    fullForm: "Funding Primary Account Number",
    category: "Finance",
    details: "Primary account numbers are not random numbers. They are made up of several sets of numbers, which serve specific purposes. The first six or eight digits in a PAN are theissuer identification number, or IIN.",
  },
  {
    id: "dpan",
    term: "DPAN",
    fullForm: "Device Primary Account Number a.k.a Digital Primary Account Number",
    category: "Finance",
    details: "SIMs are used to identify and authenticate subscribers on mobile devices. SIMs are transferable between different mobile devices by removing the card itself. SIM cards are always used on GSMphones; forCDMAphones, they are needed only forLTE-capable handsets.",
  },
  {
    id: "smart",
    term: "SMART",
    fullForm: "Specific, Measurable, Achievable, Realistic and Time-bound",
    category: "General",
    details: "S.M.A.R.T. is an acronym for Specific, measurable, assignable, realistic, and time-bound goals. The term was first proposed by George T. Doran in the November 1981 issue ofManagement Review.",
  },
  {
    id: "fed",
    term: "FED",
    fullForm: "Floor Expiry Date",
    category: "General",
    details: "Caps and floors can be used tohedgeagainst interest rate fluctuations. For example, a borrower who is paying the LIBOR rate on a loan can protect himself against a rise in rates by buying a cap.",
  },
  {
    id: "imk",
    term: "IMK",
    fullForm: "Issuer Master Key",
    category: "General",
    details: "An issuer is a legal entity that develops, registers and sells securities to finance its operations. Issuers may be corporations,investment trusts, or domestic or foreign governments.",
  },
  {
    id: "cmk",
    term: "CMK",
    fullForm: "Card Master Key",
    category: "General",
    details: "Master keyed lock systems generally reduce overall security. Amaster keyoperates a set of several locks. Usually, there is nothing different about the key. The differences are in the locks the key will operate.",
  },
  {
    id: "vcn",
    term: "VCN",
    fullForm: "Virtual Card Number",
    category: "General",
    details: "Virtual credit card is an alias for an ordinary credit card number. It can only be used for a limited number of transactions. The number is generated through the use of either a Web application or a specialized client program, interacting with the card issuer's computer.",
  },
  {
    id: "iccp",
    term: "ICCP",
    fullForm: "In Control for Commercial Payments",
    category: "Finance",
    details: "Credit control, also called credit policy, is the strategy used by a business to accelerate sales of products or services. Businesses prefer to extend credit to those with \"good\" credit and limit credit to riskier borrowers who may have a history of delinquency.",
  },
  {
    id: "fr-y-14m",
    term: "FR Y-14M",
    fullForm: "The FR Y-14M report collects monthly detailed data on bank holding companies' (BHCs), savings and loan holding companies' (SLHCs), and intermediate holding companies' (IHCs) loan portfolios.",
    category: "Finance",
    details: ".",
  },
  {
    id: "ato",
    term: "ATO",
    fullForm: "Account Takeovers",
    category: "Finance",
    details: "Takeovers are typically initiated by a larger company seeking to take over a smaller one. They can be voluntary, meaning they are the result of a mutual decision between the two companies. Takeovers are also commonly done through themerger and acquisitionprocess.",
  },
  {
    id: "hmac",
    term: "HMAC",
    fullForm: "hash-based message authentication codes",
    category: "Technology",
    details: "An HMAC is a type of keyed hash function that can also be used in a key derivation scheme or a key stretching scheme. An HMAC can provide authentication using ashared secretinstead of usingdigital signatures.",
  },
  {
    id: "recidivism-rate",
    term: "Recidivism rate",
    fullForm: "The rate at which cards move backward in the process. If a task moves to done but it's not complete or has bugs, it's moved back, thus causing the recidivism rate to go up. If you use B to represent the number of times a card moves backward and F to represent the number of times a card moves forward, then recidivism can be calculated with the formula (B / (F + B)) * 100.",
    category: "General",
    details: ".",
  },
  {
    id: "ecoa",
    term: "ECOA",
    fullForm: "Equal Credit Opportunity Act",
    category: "Finance",
    details: "The Equal Credit Opportunity Act was enacted October 28, 1974. It makes it unlawful for any creditor to discriminate against any applicant. The law applies to any person who, in the ordinary course of business, regularly participates in a credit decision.",
  },
  {
    id: "udaap",
    term: "UDAAP",
    fullForm: "Unfair deceptive or abusive acts or practices",
    category: "General",
    details: "It is illegal to engage in unfair, deceptive, or abusive acts or practices (UDAAP) The Dodd-Frank Wall Street Reform and Consumer Protection Act defined and outlawed UDAAP.",
  },
  {
    id: "fdcpa",
    term: "FDCPA",
    fullForm: "Fair Debt Collections Practices Act",
    category: "General",
    details: "The Fair Debt Collection Practices Act was approved on September 20, 1977. The Act creates guidelines under which debt collectors may conduct business, defines rights of consumers involved with debt collectors, and prescribes penalties and remedies for violations of the Act.",
  },
  {
    id: "tila",
    term: "TILA",
    fullForm: "Truth In Lending Act",
    category: "General",
    details: "TILA gives consumers the right to cancel certain credit transactions that involve alien on a consumer's principal dwelling. With the exception of certain high-costmortgage loans, TILA does not regulate the charges that may be imposed for consumer credit.",
  },
  {
    id: "aba",
    term: "ABA",
    fullForm: "American Bankers Association Routing Numbers",
    category: "General",
    details: "The American Bankers Association (ABA) developed the system in 1910. An ABA RTN is a nine-digit code printed on the bottom of a check. The ABA has partnered with a series of registrars to manage the system.",
  },
  {
    id: "ofac",
    term: "OFAC",
    fullForm: "The Office of Foreign Assets Control",
    category: "General",
    details: "OFAC administers and enforces economic and tradesanctions in support of U.S. national security. OFAC carries out its activities against foreign governments, organizations (including terrorist groups and drug cartels)",
  },
  {
    id: "rrc",
    term: "RRC",
    fullForm: "Rewards Reversal Charge",
    category: "General",
    details: "A void transaction is a debit or credit card transaction that is canceled by the merchant before it is settled by the cardholder's bank. Transactions are often voided when customers or merchants discover that an error has occurred or when fraud is suspected.",
  },
  {
    id: "tlid",
    term: "TLID",
    fullForm: "Transaction Link ID",
    category: "General",
    details: "Unique Transaction Identifier (UTI) is a globallyunique identifier. USIs were introduced in late 2012 in the U.S. in the context ofDodd–Frankregulation.",
  },
  {
    id: "mm",
    term: "MM",
    fullForm: "Mini-Miranda Rights",
    category: "General",
    details: "Mini-Miranda rights are required when a debt collector contacts you by phone, letter, or in person. You must be informed of who is calling, what they are calling about, and that they may not harass you.",
  },
  {
    id: "acmi",
    term: "ACMI",
    fullForm: "Apple Card Monthly Installment",
    category: "General",
    details: "Apple and Goldman Sachs were fined more than $89 million Wednesday. The fine follows an investigation into the Apple Card, a credit card that worked with the iPhone maker's Apple Pay platform.",
  },
  {
    id: "ccc",
    term: "CCC",
    fullForm: "Compliance Condition Code",
    category: "Technology",
    details: "Regulatory compliancedescribes the goal that organizations aspire to achieve in their efforts to ensure that they are aware of and take steps to comply with relevantlaws, policies, andregulations. In general,compliancemeans conforming to a rule, such as a specification,policy,standardorlaw.",
  },
  {
    id: "acdv",
    term: "ACDV",
    fullForm: "Automated Credit Dispute Verification",
    category: "Finance",
    details: "**ACDV** stands for *Automated Credit Dispute Verification*. It is a standardized electronic process used by credit reporting agencies and data furnishers to communicate and resolve consumer credit disputes. \n\nThe ACDV process is part of the **e-OSCAR** system (Online Solution for Complete and Accurate Reporting), where: \n- Credit bureaus receive disputes from consumers. \n- The bureau creates an ACDV form and sends it electronically to the original data furnisher (e.g., a bank). \n- The furnisher reviews and responds with corrections or verification. \n\nThis workflow ensures that disputed credit items are investigated and corrected or validated in a timely and consistent manner.",
  },
  {
    id: "aud",
    term: "AUD",
    fullForm: "Automated Universal Data Form",
    category: "Technology",
    details: "JetFormCorporation first used the term \"enterprise forms automation\" in the mid 1990s to describe their solution to automating paperwork. This process was later acquired byAdobe Systems and is now part of theAdobe LiveCyclesuite of products.",
  },
  {
    id: "bic",
    term: "BIC",
    fullForm: "Bank Identification Code",
    category: "Technology",
    details: "The BIN system helps financial institutions identify fraudulent or stolen payment cards and can help prevent identity theft. BINs can be found on various payment cards, including credit cards, charge cards, and debit cards. This set of numbers identifies thefinancial institutionthat issues the card.",
  },
  {
    id: "pan",
    term: "PAN",
    fullForm: "Primary Account Number",
    category: "Finance",
    details: "Primary account numbers are not random numbers. They are made up of several sets of numbers, which serve specific purposes. The first six or eight digits in a PAN are theissuer identification number, or IIN.",
  },
  {
    id: "iban",
    term: "IBAN",
    fullForm: "International Bank Account Number",
    category: "Finance",
    details: "An IBAN uniquely identifies the account of a customer at a financial institution. By July 2024, 88 countries were using the IBAN numbering system. The IBAN consists of up to 34 alphanumeric characters.",
  },
  {
    id: "ica",
    term: "ICA",
    fullForm: "Interbank Card Association",
    category: "General",
    details: "Mastercard is an American company that issues credit cards. The company was founded in 1979 and is based in New York City.",
  },
  {
    id: "tms",
    term: "TMS",
    fullForm: "Terminal Management System",
    category: "Technology",
    details: "ATerminal Operating System, or TOS, is a key part of a supply chain. It primarily aims to control the movement and storage of various types ofcargo. The systems also enables better use of assets, labour and equipment.",
  },
  {
    id: "mms",
    term: "MMS",
    fullForm: "Merchant Management System",
    category: "Technology",
    details: "Merchant services are services that businesses can use to accept and process electronic payments from their customers. These transactions may involve a combination of point-of-sale (POS) systems, credit card readers, payment gateways, and online transaction processing, among others.",
  },
  {
    id: "how-to-create-a-glossary",
    term: "How to create a Glossary",
    fullForm: "Steps for creating a glossary page in confluence",
    category: "General",
    details: "Landforms are categorized by characteristic physical attributes such as their creating process, shape, elevation, slope, orientation, rock exposure, and soil type.",
  },
  {
    id: "dukpt",
    term: "DUKPT",
    fullForm: "derived unique key per transaction",
    category: "General",
    details: "Derived Unique Key Per Transaction (DUKPT) is a key managementscheme in which for every transaction, a uniquekey is used. The current (as of May 2024) version of the standard (ANSI X9.24-3-2017) was released in 2017.",
  },
  {
    id: "rsa",
    term: "RSA",
    fullForm: "Rivest Shamir Adleman",
    category: "General",
    details: "The RSA cryptosystem is one of the oldest widely used for secure data transmission. Messages can be encrypted by anyone, via the public key, but can only be decrypted by someone who knows the private key. The security of RSA relies on the practical difficulty offactoring the product of two largeprime numbers, the \"factoring problem\"",
  },
  {
    id: "rrn",
    term: "RRN",
    fullForm: "Retrieval Reference Number",
    category: "General",
    details: "Run River North is an indie folk-rock band from Los Angeles, California. RRN is a key to uniquely identify a card transaction based on the ISO 8583standard.",
  },
  {
    id: "srn",
    term: "SRN",
    fullForm: "Source Registration Number",
    category: "General",
    details: "Aregistered identification number (orRN) is a number issued by theFederal Trade Commission. Such businesses are not required to have RNs. They may, however, use the RN in place of a name on the label or tag that is required to be affixed to their products.",
  },
  {
    id: "3ds",
    term: "3DS",
    fullForm: "3D Secure",
    category: "General",
    details: "Amerchant plug-in(MPI) is a software module designed to facilitate3-D Secureverifications to help preventcredit card fraud. The MPI identifies the account number and queries the servers of the card issuer.",
  },
  {
    id: "oct",
    term: "OCT",
    fullForm: "Original Credit Transaction",
    category: "Finance",
    details: "A letter of credit is a letter from a bank guaranteeing that a buyer's payment to a seller will be received on time and for the correct amount. If the buyer is unable to make a payment, the bank will be required to cover the full or remaining amount.",
  },
  {
    id: "arn",
    term: "ARN",
    fullForm: "Acquirer Reference Number",
    category: "General",
    details: "Anacquiring bank is an institution that processescreditordebit cardpayments on behalf of a merchant. The acquiring bank accepts the risk that the merchant will remainsolvent. The main source of risk to the acquiring bank is fund reversals.",
  },
  {
    id: "tcc",
    term: "TCC",
    fullForm: "Transaction Category Codes",
    category: "Technology",
    details: "Amerchant category code (MCC) is a four-digit number used for retail financial services to classify a business by the types of goods or services it provides. MCCs are assigned either by merchant type (e.g., one for hotels, one for office supply stores, etc.) or by merchant name.",
  },
] as const satisfies readonly GlossaryTerm[]
