import type { Skill } from './schema.ts'

// apps/portfolio Skills (skillSections). `use` is where the skill was used: professional, personal or learning.
export const skills = [
  { name: "Python", group: "Programming", since: "2019-01", use: "professional" },
  { name: "C", group: "Programming", since: "2010-01", until: "2020-01", use: "professional" },
  { name: "C++", group: "Programming", since: "2010-01", until: "2020-01", use: "professional" },
  { name: "JavaScript", group: "Programming", since: "2020-01", use: "personal" },
  { name: "HTML5", group: "Programming", since: "2020-01", use: "professional" },
  { name: "SQL", group: "Programming", since: "2012-01", until: "2021-01", use: "professional" },
  { name: "Java", group: "Programming", since: "2020-01", until: "2021-01", use: "learning" },
  { name: "React.js", group: "Frontend", since: "2023-01", use: "professional" },
  { name: "CSS3", group: "Frontend", since: "2020-01", use: "professional" },
  { name: "Tailwind CSS", group: "Frontend", since: "2023-06", use: "personal" },
  { name: "Sass", group: "Frontend", since: "2023-06", use: "learning" },
  { name: "Bootstrap", group: "Frontend", since: "2020-01", use: "professional" },
  { name: "Flask", group: "Frontend", since: "2021-01", use: "professional" },
  { name: "Oracle", group: "Database", since: "2010-01", until: "2019-01", use: "professional" },
  { name: "Sybase", group: "Database", since: "2015-01", until: "2020-01", use: "professional" },
  { name: "DB2", group: "Database", since: "2018-01", until: "2020-01", use: "professional" },
  { name: "PostgreSQL", group: "Database", since: "2021-01", use: "professional" },
  { name: "MS SQL", group: "Database", since: "2016-01", until: "2020-01", use: "professional" },
  { name: "MongoDB", group: "Database", since: "2022-06", until: "2023-01", use: "learning" },
  { name: "Git", group: "SCM", since: "2019-01", use: "professional" },
  { name: "SVN", group: "SCM", since: "2015-01", until: "2020-01", use: "professional" },
  { name: "GitHub", group: "SCM", since: "2019-01", use: "professional" },
  { name: "Bitbucket", group: "SCM", since: "2019-01", use: "professional" },
  { name: "Bitbucket Pipelines", group: "Cloud & DevOps", since: "2021-01", use: "professional" },
  { name: "Jenkins", group: "Cloud & DevOps", since: "2023-01", use: "personal" },
  { name: "GitHub Actions", group: "Cloud & DevOps", since: "2023-01", use: "personal" },
  { name: "AWS", group: "Cloud & DevOps", since: "2022-01", until: "2023-01", use: "professional" },
  { name: "Azure", group: "Cloud & DevOps", since: "2022-01", until: "2023-01", use: "learning" },
  { name: "Docker", group: "Cloud & DevOps", since: "2022-01", until: "2023-01", use: "learning" },
  { name: "Terraform", group: "Cloud & DevOps", since: "2022-01", until: "2023-01", use: "learning" },
  { name: "Jira", group: "Project Management", since: "2014-01", use: "professional" },
  { name: "MS Project", group: "Project Management", since: "2010-01", until: "2023-01", use: "professional" },
  { name: "Trello", group: "Project Management", since: "2023-01", use: "personal" },
  { name: "Confluence", group: "Collaboration Tools", since: "2019-01", use: "professional" },
  { name: "SharePoint", group: "Collaboration Tools", since: "2019-01", use: "professional" },
  { name: "Notion", group: "Collaboration Tools", since: "2023-01", use: "personal" },
  { name: "Selenium", group: "Testing", since: "2023-01", use: "personal" },
  { name: "Pytest", group: "Testing", since: "2021-01", use: "professional" },
  { name: "Postman", group: "Testing", since: "2023-01", use: "personal" },
  { name: "SonarQube", group: "Testing", since: "2023-01", use: "personal" },
  { name: "Plotly Dash", group: "Visualization", since: "2021-01", use: "professional" },
  { name: "Pandas", group: "Visualization", since: "2020-01", use: "professional" },
  { name: "Power BI", group: "Visualization", since: "2022-01", until: "2023-01", use: "learning" },
  { name: "Tableau", group: "Visualization", since: "2022-01", until: "2023-01", use: "professional" },
  { name: "PyCharm", group: "Dev Tools", since: "2019-01", use: "professional" },
  { name: "VS Code", group: "Dev Tools", since: "2020-01", use: "professional" },
  { name: "pip", group: "Dev Tools", since: "2019-01", use: "personal" },
  { name: "npm", group: "Dev Tools", since: "2023-01", use: "personal" },
] as const satisfies readonly Skill[]
